# Languages

zh:
  languageCode: zh-Hans
  languageName: 中文
  weight: 1
  contentDir: content/zh
  title: NIL
  params:
    language_label: 中文
    switch_label: 中文

en:
  languageCode: en-US
  languageName: English
  weight: 2
  contentDir: content/en
  title: NIL
  params:
    language_label: English
    switch_label: EN
