# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /introduction/
    weight: 10
  - name: Research
    url: /introduction/research
    weight: 11


  - name: People
    url: /people/
    weight: 20
  - name: Founding Members
    url: /people/founding_members
    weight: 1
    parent: People
  - name: Team
    url: /people/
    weight: 2
    parent: People
  - name: Contacts
    url: /contacts
    weight: 3
    parent: People


  - name: Conference
    url: /conference/
    weight: 30
    identifier: Conference
  - name: Organizers
    url: /conference/#organizers
    weight: 1
    parent: Conference
  - name: Welcome Message
    url: /conference/#welcome
    weight: 2
    parent: Conference
  - name: Schedule
    url: /conference/#schedule
    weight: 3
    parent: Conference
  - name: Venue
    url: /conference/#venue
    weight: 4
    parent: Conference

  - name: Networks
    url: networks
    weight: 40
  
  - name: Open Positions
    url: /people/open_positions
    weight: 41
  - name: News
    url: news
    weight: 50
