# Navigation Links
# The first-level navigation items link to the first page in each section.

main:
  - name: About
    identifier: about
    url: /introduction/
    weight: 10
  - name: Lab Introduction
    parent: about
    url: /introduction/
    weight: 1
  - name: Origin Story
    parent: about
    url: /introduction/origin-story/
    weight: 2
  - name: Mission & Vision
    parent: about
    url: /introduction/mission-vision/
    weight: 3
  - name: Networks
    parent: about
    url: /networks/
    weight: 4

  - name: Research
    identifier: research
    url: /introduction/research/
    weight: 20
  - name: Research Areas
    parent: research
    url: /introduction/research/
    weight: 1
  - name: Projects
    parent: research
    url: /research/projects/
    weight: 2
  - name: Publications / Outputs
    parent: research
    url: /publication/
    weight: 3

  - name: People
    identifier: people
    url: /people/
    weight: 30
  - name: Founding Members
    parent: people
    url: /people/founding_members/
    weight: 1
  - name: Teams
    parent: people
    url: /people/
    weight: 2

  - name: Opportunities
    identifier: opportunities
    url: /opportunities/
    weight: 40
  - name: Research Positions
    parent: opportunities
    url: /opportunities/research-positions/
    weight: 1
  - name: Graduate Admission
    parent: opportunities
    url: /opportunities/graduate-admission/
    weight: 2
  - name: Undergraduate Research
    parent: opportunities
    url: /opportunities/undergraduate-research/
    weight: 3
  - name: Visiting Students
    parent: opportunities
    url: /opportunities/visiting-students/
    weight: 4
  - name: Summer School
    parent: opportunities
    url: /events/summer-schools/
    weight: 5

  - name: News & Events
    identifier: news-events
    url: /events/
    weight: 50
  - name: Lab News
    parent: news-events
    url: /news/
    weight: 1
  - name: Conferences
    parent: news-events
    url: /events/conferences/
    weight: 2
  - name: Summer Schools
    parent: news-events
    url: /events/summer-schools/
    weight: 3
  - name: Reports & Talks
    parent: news-events
    url: /events/reports-talks/
    weight: 4

  - name: Contact
    url: /contacts/
    weight: 60
